carveracontroller/GcodeViewer.py
Needs to load .obj 3d files based on `__file__` reference
=> Fix #19 #18

.github/workflows/release.yaml
=> use tschm/token-mint-action and poetry for publishing

.github/workflows/release.yaml, CHANGELOG.md, carveracontroller/__version__.py, carveracontroller/main.py, poetry.lock, pyproject.toml, scripts/build.py, scripts/rename-release-file.sh
- Change: Use the Carvera-Community URLs for update checking  #7 
- Fix: Show the top of update log on load instead of the bottom #50
=> Version update tracker

CHANGELOG.md, carveracontroller/main.py, carveracontroller/makera.kv
=> Default to last local dir

CHANGELOG.md, carveracontroller/Controller.py, carveracontroller/makera.kv
Fire M490.1 and M490.2 respectively
Useful for quick manual tool changes
=> Adding clamp and unclamp buttons to tool dropdown

CHANGELOG.md, carveracontroller/main.py
=> Set default upload file callback

CHANGELOG.md, carveracontroller/Controller.py, carveracontroller/main.py, carveracontroller/makera.kv
=> Bug report button opens log dir

CHANGELOG.md, carveracontroller/controller_config.json, carveracontroller/main.py, carveracontroller/makera.kv
This is PR adds a Controller config screen resolving these issues:
#104 
#107
#106 
#105
=> Controller Configuration Settings and UI Enhancements

carveracontroller/main.py
=> Fix UI density override

CHANGELOG.md, carveracontroller/Controller.py, carveracontroller/main.py, carveracontroller/makera.kv
Implements Advanced Jog Controls. Additional controls panel for jogging. Including Ability to set jog movement speed and Keyboard Mode. When keyboard mode is enabled, use Arrow keys for X/Y, and PgUp/PgDown for Z axis movements.
=> Keyboard based jogging

CHANGELOG.md, carveracontroller/addons/tooltips/Tooltips.kv, carveracontroller/addons/tooltips/Tooltips.py, carveracontroller/main.py, carveracontroller/makera.kv
change a Button to a ToolTipButton
DropDown to ToolTipDropDown
Label to ToolTipLabel
Optional parameters
tooltip_txt: tr._('text here')
tooltip_image: 'path/to/image.png'
tooltip_image_size: [100,100]
If no image or text is given the tooltip will not show up.
Eventually I should add a global override to disable/enable tooltips in the controller settings.
=> adding dynamic tooltip function to the controller

CHANGELOG.md, carveracontroller/main.py
=> Adds copy handler to MDI lists

CHANGELOG.md, carveracontroller/Controller.py, carveracontroller/main.py, carveracontroller/makera.kv
The stock firmware allows tools up to 256 (it looks like they are planning to increase that to 1000) The community firmware allows tools up to 99999
=> adding set and change to custom tool number in dropdown

CHANGELOG.md, scripts/update_translations.py
Updatetraslations.py now uses an rglob search through the directory for .py and .kv files instead of having to manually add each new file to an array
=> Update translations To Use Global Search

CHANGELOG.md, carveracontroller/makera.kv
=> Light switch

.github/workflows/release.yaml, CHANGELOG.md, README.md
=> Updated Github Action Runners

CHANGELOG.md, carveracontroller/makera.kv
=> Better manual probe thickness text

.github/workflows/dev-release.yaml, scripts/build.py
* Windows can't handle leading zeros in version
* Missing version string in appimage build
=> Fix dev build workflow

CHANGELOG.md, carveracontroller/main.py, carveracontroller/makera.kv
3D Probe is an option in the "Set" Tool menu and recognized in the status bar. This sets the tool to number 99990.
=> 3D Probe in Tool Selection (Set Menu)

CHANGELOG.md, carveracontroller/Controller.py, carveracontroller/main.py, carveracontroller/makera.kv
=> Start Gcode playback at line in UI

.github/workflows/release.yaml
=> CI Update artifact release paths

CHANGELOG.md, README.md, buildozer.spec, packaging_assets/android/recipes/pyquicklz/__init__.py, scripts/build.py
This should cover 99% of the android devices on the market, based on that I've dropped the arch from the filename
=> added armv8 and x86_64 support to the apk package

.github/workflows/release.yaml, README.md, scripts/install_linux_prereqs.sh
Added Linux Pendant dependency information to README and moved Linux deps install to script for CI purposes
=> Linux Pendant dependency and CI simplification

scripts/build.py
- Update environment variable for linuxdeploy output version 
- Correct AppImage file extension as expected by CI
=> Fix Linux AppImage Build

CHANGELOG.md, carveracontroller/main.py, carveracontroller/makera.kv
- Change: Light toggle button initial state is set on connect
=> Update light toggle button state on connection

CHANGELOG.md, carveracontroller/Controller.py, carveracontroller/main.py, carveracontroller/makera.kv
Fixes:
- Macro button text was being set to macro key if unset
- Better handling of machine diagnostic output to support analogue mode spindles
- Fix XYZ Probing
- Log MDI sent/recived to log file
=> Small bug fixes

CHANGELOG.md
forgot to update the changelog
=> Changelog for path origin skip

CHANGELOG.md, carveracontroller/main.py
Pushing Cancel on the Changing Tool popup stops g-code playback
=> Pushing Cancel on the Changing Tool popup stops g-code playback

CHANGELOG.md, carveracontroller/addons/probing/ProbingPopup.kv, carveracontroller/main.py
=> App jogging

CHANGELOG.md, carveracontroller/Controller.py, carveracontroller/main.py, carveracontroller/makera.kv
=> Autoreconnection failure dialog now only shown on failure of last attempt, previously was shown on every attempt

CHANGELOG.md, carveracontroller/Controller.py, carveracontroller/main.py
=> Closing the Controller after auto-reconnection canceled causes the app to freeze
